### ISSUE TITLE
Onboarding improvements

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/.github#10]
From @alessandratrapani's presentation at the retreat

Make an onboarding checklist

- how to use toggl (official company policy statement would be nice)
- how to use github
- how to use slack
- how to use globus (existing docuemnts just add link)
- how to use rclone and the google drive

How to approach a conversion project
- NWB self-training (youtube videos, but in a recommended order, etc)
- CN GitHub workflow intro
- conversion project example, hopefully a small simple one, but could be any active project right now?

Also move NeuroConv coding style here

**Comment by CodyCBakerPhD** [comment]
Also persistent links to cookiecutters we use for extensions and conversion repos

**Comment by CodyCBakerPhD** [comment]
From @alejoe91, how to setup the privateemail and calendly with gmail

**Comment by CodyCBakerPhD** [comment]
Also just gmail instructions

**Comment by CodyCBakerPhD** [comment]
Add standard templates that we client communications (primarily for conversion projects)

Possibly compile standard scope templates (which might be the point at which this because a private docs repo rather than the public location here)

**Comment by CodyCBakerPhD** [comment]
But client instructions (simplified description of our policies, such as why we like acquisition formats rather than ad hoc parsed forms) would need to be public

**Comment by pauladkisson** [comment]
Some other learning bottlenecks/pain points I've run into in the onboarding process:
- aws cli
- Understanding how the nwb ecosystem fits together: hdf5, hdmf, pynwb, nwb-extensions, neuroconv, spikeinterface, etc.
- best practices with testing and documentation
- Github tooling
  - pre-commit hooks
  - CI / Actions and Workflows
  - readthedocs
