### ISSUE TITLE
relax docstring requirements

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/.github#17]
The docstring checks are a great idea but I think as they currently stand they are a bit too strict for adoption across our repos. I would like to request 3 changes:

**1. Functions and methods.** I think it makes sense to enforce that all functions and methods must either be marked as private with a `_` or have a docstring, especially since it appears this is critical for autodoc to work. For private methods, this should not be enforced.

**2. modules.** For modules, I have found it annoying and often repetitive to need to create docstrings for basic `__init__.py` files. 
For example these lines:

https://github.com/catalystneuro/roiextractors/blob/da6d79103d5841cae3c2087d230fc18f608c4a4a/src/roiextractors/extractors/hdf5imagingextractor/hdf5imagingextractor.py#L1-L7

are repetitive with these lines:

https://github.com/catalystneuro/roiextractors/blob/da6d79103d5841cae3c2087d230fc18f608c4a4a/src/roiextractors/extractors/hdf5imagingextractor/__init__.py#L1-L13

Would it be possible to relax the check so that the `__init__.py` files were skipped? A developer could still write a docstring for these, but I don't think it should be required.

**3. More flexibility.** Could we add parameters that allows this check to skip modules or to skip functions?

**4. File organization** Could we separate workflows from workflow definitions? Currently, `call_check_docstrings.yaml` is in the same directory is `check_docstrings.yml`, which I find confusing. I think `.github/workflows` should be reserved for files that are specifying workflows to be run on that repo, so `call_check_docstrings.yaml` should be there (possibly renamed to `check_docstrings.yaml`) and the current `check_docstrings.yml` should be moved to `/workflow_definitions`.

**Comment by CodyCBakerPhD** [comment]
Thanks for the feedback

1. Sounds good, fine with relaxing that

2.

I'd argue a couple things here

First that the `__init__.py` file of all properly exposed public submodules are among the **most important** things to provide help for - you can take that opportunity to summarize what the publically exposed submodule is there to do as an API, how to call and use various methods within it, or just embed a hyperlink to relevant parts of the main docs

Both`numpy` and `sklearn` believe strongly in this as evidenced by both their main modules ([`import numpy; numpy?`](https://github.com/numpy/numpy/blob/main/numpy/__init__.py) and [`import sklearn; sklearn?`](https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/__init__.py)) and popular/important submodules (such as [`numpy.linalg`](https://github.com/numpy/numpy/blob/main/numpy/linalg/__init__.py) and [`sklearn.< well, you can pick any of them really; here is decomposition >`](https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/decomposition/__init__.py#L1-L5))

Second is that in the cases you mention I believe the public submodules are too overexposed. The first-order submodule [`roiextractors.extractors`](https://github.com/catalystneuro/roiextractors/tree/da6d79103d5841cae3c2087d230fc18f608c4a4a/src/roiextractors/extractors) has more than ten entries for second-order submodules when all it really needs to do is expose the relevant extractor classes

And these second-order submodules are also overexposed with duplicated names as well; consider your example of `roiextractors.extractors.hdf5imagingextractor.hdf5imagingextractor` (a third-order submodule). As it is publically exposed we essentially say it is allowed to do
```python
from roiextractors.extractors.hdf5imagingextractor.hdf5imagingextractor import HDF5ImagingExtractor
```

but of course we would always encourage the simpler `from roiextractors.extractors import HDF5ImagingExtractor`

In line with (1), if any order submodule is marked as private (e.g., `roiextractors.extractors._hdf5`) then in that case the documentation of the `__init__.py` matters not at all and can/should be skipped from the checker

So if we enforced better scoping for our packages, the `__init__.py` of public submodules would become very important to check docstrings for

3.  Absolutely. Some `pyproject.toml` or inputs-based skipping support would be great and make it just like any other linting tool

4.

Yes, it should at the very least be an `action` [like Heberto made recently](https://github.com/catalystneuro/neuroconv/blob/main/.github/actions/install-wine/action.yml) whereas the workflow would be the thing that calls the action. That should not be hard at all to adjust

Or even better, make it a pre-commit hook and just add 3 lines in our `.pre-commit.yaml` files

**Comment by pauladkisson** [comment]
4. `call_check_docstrings.yaml` is really just a workflow to test `check_docstrings.yml` as it would be used by other repos in our ecosystem (ex. roiextractors). This confusion could probably be resolved just by renaming it and maybe adding a comment at the top.

**Comment by bendichter** [comment]
2. @CodyCBakerPhD OK, fair points with numpy and sklearn. I guess in many cases these docstrings are really just a title, which is not too bad. However, note that in numpy, not all modules have docstrings, e.g. https://github.com/numpy/numpy/blob/main/numpy/linalg/linalg.py and some inits don't have docstrings: https://github.com/numpy/numpy/blob/main/numpy/strings/__init__.py. I just don't like making things required unless we think they should **really** be required. Otherwise, we just bog ourselves down in our own red tape. Requiring a single sentence I guess is fine, but at least in the case of numpy I would argue their use of docstrings violates the DRY principle. e.g. [here](https://github.com/numpy/numpy/blob/416bc199599cad58ca5ecf9f4517de70eb38e67c/numpy/polynomial/polyutils.py#L1-L20) they have summaries for the functions, but I think that should just be the first line of the docstring of each function.


.4. @pauladkisson it's more about reserving the `workflows` dir for workflows. I like @CodyCBakerPhD 's suggestion of creating an `actions` directory to hold actions.

**Comment by h-mayorquin** [comment]
Relevant documentation for workflows vs actions for avoiding duplication of code in the github actions platform:

https://docs.github.com/en/actions/sharing-automations/avoiding-duplication
