### ISSUE TITLE
Add helpdesk?

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/.github#2]
NeurodataWithoutBorders and DANDI both have a general helpdesk location for questions/difficulties spanning the ecosystem.

Should we have one as well? Thoughts? @h-mayorquin @luiztauffer @bendichter

**Comment by bendichter** [comment]
These are useful when there are issue from external users that are not necessarily associated with specific repos. It's hard to imagine in our care an external user would have a question that isn't related to a specific repo, but I'd be open to creating one if you all think it would be useful.

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin @weiglszonja @alejoe91 @luiztauffer What are your votes on this? Would this be useful or should I close?

**Comment by weiglszonja** [comment]
I don't think there is a demand for it right now, but maybe we could have a section in `README.md `that would ease the navigation between the repos? 

 "If you have any questions you can reach us here and there" or even point them directly to the example gallery or tutorials in Neuroconv? Didn't find what you were looking for? You can reach us ... 

Also maybe not connected to this topic, but we could also list our appearances in workshops or conferences like where to find us?

**Comment by h-mayorquin** [comment]
I share the opinion of @bendichter that probably issues are enough.

**Comment by CodyCBakerPhD** [comment]
> but maybe we could have a section in README.md that would ease the navigation between the repos?

The landing page https://github.com/catalystneuro has the repo navigation stuff, is that sufficient?

> "If you have any questions you can reach us here and there" or even point them directly to the example gallery or tutorials in Neuroconv? Didn't find what you were looking for? You can reach us ...

We *kind of* have that peppered throughout the new issue pages (like https://github.com/catalystneuro/neuroconv/issues/new/choose) but those are all repo specific, no global contact available. What would be the best way to implement that? Add an extra section in the landing page README?

> but we could also list our appearances in workshops or conferences like where to find us?

I think we have that on the main website to a certain extent but IDK how often it gets updated: https://www.catalystneuro.com/portfolio/

**Comment by CodyCBakerPhD** [comment]
Conclusion: no help desk until needed, keep submissions repo-specific on issues.
